server:
  port: ${PORT:8080}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    metadata-map:
      instanceId: ${spring.application.name}
    lease-renewal-interval-in-seconds: 10
health:
  hystrix:
    enabled: true