server:
  port: ${PORT:8080}
logging:
  level:
    microservices.demo: DEBUG
configuration:
  demo-name: Microservice Demo App
  demo-version: 0.1
  account-service-url: http://localhost:18081
  card-service-url: http://localhost:19081