eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    metadata-map:
      instanceId: ${spring.application.name}
    lease-renewal-interval-in-seconds: 10